version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 2
    reset_on_push:
      enabled: true
    users:
    - dash1291
    - vaidik
    - amanmehta25
    - nimishsinghal
